xy_plot:
  MAP_FRAME_PEN: black
  FONT_ANNOT_PRIMARY: 16p,Times-Roman
  FONT_LABEL: 16p,Times-Roman,black
  MAP_GRID_PEN_PRIMARY: thinner,grey
  
xy_region: [-5, 5, -1.5, 1.5]
  
region_map:
    MAP_FRAME_PEN: black
    MAP_FRAME_WIDTH: 6p
    FONT_ANNOT_PRIMARY: 16p,Times-Roman
    FONT_LABEL: 16p,Times-Roman,black
    MAP_GRID_PEN_PRIMARY: thinner,grey
    FORMAT_GEO_MAP: ddd.xx
    
moriches_map:
    region: [-72.87995372, -72.65004631, 40.72, 40.829954]
    basemap_frame: ['ya.02f.01+l"Latitude"', 
                    'xa.05f.025+l"Longitude"']
    colorbar_position: 'JBC+o2.05c/-1.85c+w15/.75h+mc'
    colorbar_frame: 'xaf'
    inset_region: [-72.883723, -72.841866, 40.732400, 40.753449]
    plot:
        surge_color: '#009E73'
        gauge_colors:
            west: '#0072B2'
            central: '#D55E00'
            east: '#56B4E9'
        marker_size: 0.45 # in cm
    